### ISSUE TITLE
Problem with rcvbuff size and setop

### ISSUE THREAD

**Issue by MatteoMagnani92** [marcocipriani/server-simple#11]
Se il file è troppo grande per essere anche solo contenuto nel buffer di ricezione comunque client e server chiudono con esito positivo il 3-way handshaking (sbagliando), in seguito:
- il client invia ack negativo (visto che nn può contenere il file) e per lui l'operazione è chiusa
- il server invece prova ad inviarglielo (visto che l'handshaking è positivo)  aspettando gli ack dal client che nn riceverà mai.

**Comment by marcocipriani** [comment]
Solved with continuous writing when packet processed.
