### ISSUE TITLE
Problem for initseqserver && nextseqnum

### ISSUE THREAD

**Issue by MatteoMagnani92** [marcocipriani/server-simple#13]
Il codice funziona perchè sono stare rese globali, ma per più processi dovremmo rivedere alcune funzioni (es. setop) in quanto dobbiamo passargli per riferimento tali indici dei pacchetti (sono importanti in quanto ovviamente regolano tutto il trasferimento/ricezione dei file)

**Comment by marcocipriani** [comment]
Nextseqnum passed in thread info (receiver or sender).
